data_dir: data  

backend:
gpus: 1
logger: "tensorb"

dataset: PatchCIFAR10

lr: 0.05
batch_size: 256
num_worker: 4
epoch: 200

base_model: "resnet18"
patch_size: 16
patch_stride: 8
num_uppmodels: 1
adapt_net: False
upp_loss_ratio: 1.0
drop_rate: 0.0
